/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as PracticesRouteImport } from './routes/practices'
import { Route as SystemsRouteImport } from './routes/systems'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesRoute = PracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/intelligence': typeof IntelligenceRoute
  '/practices': typeof PracticesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/intelligence': typeof IntelligenceRoute
  '/practices': typeof PracticesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/intelligence': typeof IntelligenceRoute
  '/practices': typeof PracticesRoute
  '/systems': typeof SystemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atlas' | '/intelligence' | '/practices' | '/systems'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atlas' | '/intelligence' | '/practices' | '/systems'
  id: '__root__' | '/' | '/atlas' | '/intelligence' | '/practices' | '/systems'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  IntelligenceRoute: typeof IntelligenceRoute
  PracticesRoute: typeof PracticesRoute
  SystemsRoute: typeof SystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices': {
      id: '/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  IntelligenceRoute: IntelligenceRoute,
  PracticesRoute: PracticesRoute,
  SystemsRoute: SystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
